### ISSUE TITLE
Why do the hubot name/alias has to prefix the sentence for response ?

### ISSUE THREAD

**Issue by cpmilan** [ojacques/hubot-apiai#6]
Hi Olivier,

first of, thanks a lot for your amazing work, hubot-apiai is great and helps me a lot!
Question title says it all, is there a way to pass a request to the bot without calling its name each time? Although I can understand the use case for it (group chat), I feel the "conversation" would flow more smoothly without it in 1:1 chats with the bot.

Thanks!
Guillaume

**Comment by kavya05** [comment]
even i have the same question, can anyone provide the answer please?

**Comment by ojacques** [comment]
@cpmilan, @kavya05 - the fact that the bot needs to be named is because I use `robot.respond` at [this line](https://github.com/ojacques/hubot-apiai/blob/master/src/apiai.coffee#L28).
I guess one could use `robot.hear` instead, but I did not want to trigger like this initially. But it could be an option driven by an environment variable.

Could anyone of you help with a pull request? 

More details [on respond/hear here](https://github.com/hubotio/hubot/blob/master/docs/scripting.md#hearing-and-responding).

**Comment by kavya05** [comment]
@cpmilan @ojacques  when i discussed the same topic with one of the developer of hubot he had to say this : 
![image](https://user-images.githubusercontent.com/30457237/37278423-a6951708-260d-11e8-81de-603f7199c366.png)
